# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29a247baf16b7b9b8c1f628f219859b23013d91f08cf1621b5d1e1192c607631ec812abb8150e0bbfcb975cc9411435f9698b552d8b5edc70bf0995bdf89adb0

test:
  secret_key_base: 271e2fa33997b6fbf295c0ff419ccba1f85f18fb5a424b27a8e432895bf76fd7a5091c87982a36efa8a5e73b0da8f84c2eb7546b0c22ea9c6e3d390fa3f56fdf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
